apiVersion: v1
kind: Service
metadata:
  name: zerossl-bot-service
spec:
  type: NodePort
  selector:
    app: zerossl-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 80
