apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter
  template:
    metadata:
      labels:
        app: flutter
    spec:
      restartPolicy: Always
      containers:
        - name: flutter
          image: itailavi/email-client:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: ssl-volume
      volumes:
        - name: ssl-volume
          persistentVolumeClaim:
            claimName: ssl-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: flutter-service
spec:
  selector:
    app: flutter
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 443